name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'http://internshipsmanager.herokuapp.com/'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'http://internshipsmanager.herokuapp.com/'
    needs: deploy-dev
    steps:
      - name: Deploy application on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_key: "${{secrets.HEROKU_API_KEY}}"
          heroku_app_name: "internshipsmanager"
          heroku_email: "djalmahenry@outlook.com"
          appdir: "frontend"
